// <auto-generated />
using Carbase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carbase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005164141_AddTuner")]
    partial class AddTuner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carbase.Models.Car.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int?>("HorsePower")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<decimal?>("Time0To100")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Time100To200")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Time200To250")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TimeQuarterMile")
                        .HasColumnType("numeric");

                    b.Property<int?>("TopSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("TorqueNm")
                        .HasColumnType("integer");

                    b.Property<string>("Tuner")
                        .HasColumnType("citext");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "Model", "Year", "Tuner")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Brand", "Model", "Year", "Tuner"), false);

                    b.ToTable("Cars", "carbase");
                });
#pragma warning restore 612, 618
        }
    }
}
